### ISSUE TITLE
[question] time series

### ISSUE THREAD

**Issue by lkaniak** [Brett-Kennedy/CountsOutlierDetector#4]
Hello there,

I want to know if you ran any tests on time series and how it performs in such data. Does it provide a reasonable explanation about an anomaly? Have you seen the alibi-detect packages, and if so how this compares to them?

Thanks for your time, great post on TDS tho.

**Comment by Brett-Kennedy** [comment]
Yes, I cover time series data in my book, Outlier Detection in Python,
https://www.manning.com/books/outlier-detection-in-python.

It's quite possible to do outlier detection with time series. Counts
Outlier Detector is designed for tabular data, which is a bit different,
though time series data can be converted to tabular format.

I have used Alibi-Detect and cover that in the book as well. In general, it
works well, but all outlier detectors are a bit different, and all
emphasize, and all miss, different types of anomalies.

Brett
